# Generated by Django 4.1.7 on 2023-03-13 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_assessment_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='Question')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mc_questions', to='assessments.assessment')),
            ],
            options={
                'verbose_name': 'Multiple Choice Question',
                'verbose_name_plural': 'Multiple Choice Questions',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='Content')),
                ('is_correct', models.BooleanField(default=False, help_text='Is this correct answer?', verbose_name='Is Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='questions.mcquestion')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
    ]
