# Generated by Django 4.1.7 on 2023-03-12 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('MCQ', 'MCQ'), ('SHORT_ANSWER', 'Short Answer'), ('TRUE_FALSE', 'True False')], max_length=50, verbose_name='Type')),
                ('difficulty', models.CharField(choices=[('ENTRY_LEVEL', 'Entry Level'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], max_length=50, verbose_name='Difficulty')),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming'), ('PERSONALITY', 'Personality'), ('COGNITIVE', 'Cognitive'), ('LANGUAGE', 'Language')], max_length=50, verbose_name='Category')),
                ('slug', models.SlugField(blank=True, max_length=6, null=True, verbose_name='Slug')),
                ('duration', models.PositiveIntegerField(default=600, verbose_name='Duration')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assessment_attempts', to='assessments.assessment')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobseeker_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
