# Generated by Django 4.1.7 on 2023-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
